// Generated by CoffeeScript 1.10.0
(function() {
  var client, combined$, double, flyd, frank$, hello$, inc$, somata, taglog;

  somata = require('./');

  flyd = require('flyd');

  client = new somata.Client;

  inc$ = client.on('random-events', 'inc');

  hello$ = client.on('random-events', 'hello');

  taglog = function(t) {
    return function(v) {
      return console.log("[" + t + "]", v);
    };
  };

  double = function(v) {
    return v * 2;
  };

  inc$.map(double).map(taglog('v*2'));

  inc$.map(taglog('v'));

  combined$ = flyd.stream([inc$, hello$], function() {
    return {
      hello: hello$(),
      inc: inc$()
    };
  });

  frank$ = flyd.stream([hello$], function(self) {
    if (hello$() === 'Hi Frank') {
      self(hello$.val);
    }
  });

  combined$.map(taglog('combined'));

  frank$.map(taglog('frank'));

}).call(this);
