// Generated by CoffeeScript 1.9.1
(function() {
  var client, flyd, gotMotion, motion$, somata;

  somata = require('./');

  flyd = require('flyd');

  client = new somata.Client;

  motion$ = client.on('maia:smartthings', 'motion');

  gotMotion = function(m) {
    return console.log('[m]', m);
  };

  flyd.on(gotMotion, motion$);

}).call(this);
